### ISSUE TITLE
[FEAT] Ai API 기능 개발

### ISSUE THREAD

**Issue by yoaruku** [Namgyu-The-Best-Cat/Delivery#33]
## To-Do List

- [x] AI 메뉴설명 요청
- [x] 요청메세지, 응답메세지 DB 적재
- [x] AI 메뉴설명 응답
