### ISSUE TITLE
[FIX] 에러 공통 양식 적용

### ISSUE THREAD

**Issue by yoaruku** [Namgyu-The-Best-Cat/Delivery#45]
## 이슈 설명
일반 오류처리하던 방식을 공통 양식 적용시켜 처리

## To-Do List

- [x] Menu API Exception처리
- [x] Review API Exception처리
- [x] Ai API Exception처리
